from guppy import hpy
import gc
from memtest_iters import *

h = hpy()
print('start')
print(h.heap())
from memtest import *
print('imported')
print(h.heap())
print('------------- cmd -------------')
pp_iteration(test_iteration_cmd,1000000)
print('pp_iteration(test_iteration_cmd,1000000)')
print(h.heap())
print('------------- qdet_int -------------')
pp_iteration(test_iteration_qdet_int,1000000)
print('pp_iteration(test_iteration_qdet_int,1000000)')
print(h.heap())
print('------------- nondet -------------')
pp_iteration(test_iteration_nondet,1000000)
print('pp_iteration(test_iteration_nondet,1000000)')
print(h.heap())
print('------------- py_xsb xfer -------------')
py_to_xsb_list_xfer(1000000)        
print('py_to_xsb_list_xfer(1000000)')        
print(h.heap())
print('------------- xsb_py xfer -------------')
xsb_to_py_list_xfer(1000000)        
print('xsb_to_py_list_xfer(1000000)')        
print(h.heap())
print('------------- qdet_tuple -------------')
print('test_iteration_qdet_tuple(1000000)')
pp_iteration(test_iteration_qdet_tuple,1000000)
print(h.heap())
print('------------- qdet_dict -------------')
print('test_iteration_qdet_dict(1000000)')
pp_iteration(test_iteration_qdet_dict,1000000)
print(h.heap())
print('------------- px_comp -------------')
print('test_iteration_comp(1000000)')
pp_iteration(test_iteration_comp,1000000)
print(h.heap())
print('------------- summary: gc.get_stats  -------------')
print(gc.get_stats())
print('------------- summary: gc.garbage  -------------')
print(gc.garbage)
