import sys
sys.path.insert(0,'../../XSB/packages/janus/janus-py')
import janus as jns

orig_output = sys.stdout 
sys.stdout = open('./temp', 'w')

#print('Expect slight differences between (...) and (...), due to set creation in Python')

def test_comps():
#    pp_jns_comp('px_test','test_comp')
    X = sorted(jns.comp('jns_test','test_comp'))
    print("jns_comp('jns_test','test_comp') = " + str(X))
    print('------------------------')
#    pp_jns_comp('jns_test','test_comp','e')
    X = sorted(jns.comp('jns_test','test_comp','e'))
    print("jns_comp('jns_test','test_comp)' = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp',vars=2)
    X = sorted(jns.comp('jns_test','test_comp',vars=2))
    print("jns_comp('jns_test','test_comp',vars=2) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp',truth_vals=PLAIN_TRUTHVALS)
    X = sorted(jns.comp('jns_test','test_comp',truth_vals=jns.PLAIN_TRUTHVALS))    
    print("jns_comp('jns_test','test_comp',truth_vals=PLAIN_TRUTHVALS) = " + str(X))    
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp',set_collect=True)
    X = sorted(jns.comp('jns_test','test_comp',set_collect=True))
    print("jns_comp('jns_test','test_comp',set_collect=True) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp','e',set_collect=True)
    X = sorted(jns.comp('jns_test','test_comp','e',set_collect=True))
    print("jns_comp('jns_test','test_comp','e',set_collect=True) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp',vars=2,set_collect=True)
    X = sorted(jns.comp('jns_test','test_comp',vars=2,set_collect=True))
    print("jns_comp('jns_test','test_comp',vars=2,set_collect=True) = " + str(X))
    print('------------------------')
    
    #    pp_jns_comp('jns_test','test_comp',truth_vals=DELAY_LISTS)
    X = sorted(jns.comp('jns_test','test_comp',truth_vals=jns.DELAY_LISTS))
    print("jns_comp('jns_test','test_comp',truth_vals=DELAY_LISTS) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp','e',truth_vals=DELAY_LISTS)
    X = sorted(jns.comp('jns_test','test_comp','e',truth_vals=jns.DELAY_LISTS))
    print("jns_comp('jns_test','test_comp','e',truth_vals=DELAY_LISTS) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp',vars=2,truth_vals=DELAY_LISTS)
    X = sorted(jns.comp('jns_test','test_comp',vars=2,truth_vals=jns.DELAY_LISTS))
    print("jns_comp('jns_test','test_comp',vars=2,truth_vals=DELAY_LISTS) = " + str(X))
    print('------------------------')

    #    pp_jns_comp('jns_test','test_comp',truth_vals=NO_TRUTHVALS)
    X = sorted(jns.comp('jns_test','test_comp',truth_vals=jns.NO_TRUTHVALS))
    print("jns_comp('jns_test','test_comp',truth_vals=NO_TRUTHVALS) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp','e',truth_vals=NO_TRUTHVALS)
    X = sorted(jns.comp('jns_test','test_comp','e',truth_vals=jns.NO_TRUTHVALS))
    print("jns_comp('jns_test','test_comp','e',truth_vals=NO_TRUTHVALS) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','test_comp',vars=2,truth_vals=NO_TRUTHVALS)
    X = sorted(jns.comp('jns_test','test_comp',vars=2,truth_vals=jns.NO_TRUTHVALS))
    print("jns_comp('jns_test','test_comp',vars=2,truth_vals=NO_TRUTHVALS) = " + str(X))
    print('------------------------')

    #    pp_jns_comp('jns_test','table_comp')
    X = sorted(jns.comp('jns_test','table_comp'))
    print("jns_comp('jns_test','table_comp') = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','table_comp','e')
    X = sorted(jns.comp('jns_test','table_comp','e'))
    print("jns_comp('jns_test','table_comp','e') = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','table_comp',vars=2)
    X = sorted(jns.comp('jns_test','table_comp',vars=2))
    print("jns_comp('jns_test','table_comp',vars=2) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','table_comp','e',truth_vals=PLAIN_TRUTHVALS)
    X = sorted(jns.comp('jns_test','table_comp','e',truth_vals=jns.PLAIN_TRUTHVALS))
    print("jns_comp('jns_test','table_comp','e',truth_vals=PLAIN_TRUTHVALS) = " + str(X))
    print('------------------------')

    #    pp_jns_comp('px_test','table_comp',set_collect=True)
    X = sorted(jns.comp('jns_test','table_comp',set_collect=True))
    print("jns_comp('jns_test','table_comp',set_collect=True) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','table_comp','e',set_collect=True)
    X = sorted(jns.comp('jns_test','table_comp','e',set_collect=True))
    print("jns_comp('jns_test','table_comp','e',set_collect=True) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','table_comp',vars=2,set_collect=True)
    X = sorted(jns.comp('jns_test','table_comp',vars=2,set_collect=True))
    print("jns_comp('jns_test','table_comp',vars=2,set_collect=True) = " + str(X))
    print('------------------------')

#    pp_jns_comp('jns_test','table_comp',truth_vals=DELAY_LISTS)
    X = sorted(jns.comp('jns_test','table_comp',truth_vals=jns.DELAY_LISTS))
    print("jns_comp('jns_test','table_comp',truth_vals=DELAY_LISTS) = " + str(X))
    print('------------------------')
#    pp_jns_comp('jns_test','table_comp','e',truth_vals=DELAY_LISTS)
    X = sorted(jns.comp('jns_test','table_comp','e',truth_vals=jns.DELAY_LISTS))
    print("jns_comp('jns_test','table_comp','e',truth_vals=DELAY_LISTS) = " + str(X))
    print('------------------------')
    #   pp_jns_comp('jns_test','table_comp',vars=2,truth_vals=DELAY_LISTS)
    X = sorted(jns.comp('jns_test','table_comp',vars=2,truth_vals=jns.DELAY_LISTS))
    print("jns_comp('jns_test','table_comp',vars=2,truth_vals=DELAY_LISTS) = " + str(X))
    print('------------------------')

    #    pp_jns_comp('jns_test','table_comp',truth_vals=NO_TRUTHVALS)
    X = sorted(jns.comp('jns_test','table_comp',truth_vals=jns.NO_TRUTHVALS))
    print("jns_comp('jns_test','table_comp',truth_vals=NO_TRUTHVALS)( = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','table_comp','e',truth_vals=NO_TRUTHVALS)
    X = sorted(jns.comp('jns_test','table_comp','e',truth_vals=jns.NO_TRUTHVALS))
    print("jns_comp('jns_test','table_comp','e',truth_vals=NO_TRUTHVALS) = " + str(X))
    print('------------------------')
    #    pp_jns_comp('jns_test','table_comp',vars=2,truth_vals=NO_TRUTHVALS)
    X = sorted(jns.comp('jns_test','table_comp',vars=2,truth_vals=jns.NO_TRUTHVALS))
    print("jns_comp('jns_test','table_comp',vars=2,truth_vals=NO_TRUTHVALS) = " + str(X))
    print('------------------------')

test_comps()

sys.stdout = orig_output
